name: Catalyst-Model-Oryx
version: 0.01
abstract: Oryx Object Persistence Model component for Catalyst
author: Richard Hundt <richard NO SPAM AT protea-systems.com>
license: artistic
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.6.1
  Oryx: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
